add_newline = false
format = "$directory$git_branch$git_status$nix_shell${custom.wares_shell}$character"

[directory]
style = "bold blue"
truncation_length = 3
truncation_symbol = "…/"

[character]
success_symbol = "[>](bold green)"
error_symbol = "[<](bold red)"

[nix_shell]
format = "[$symbol](bold cyan) "
symbol = "󱄅"

[custom.wares_shell]
command = 'echo 󰏖'
when = '[[ "$WARES_SHELL_ACTIVE" == "true" ]]'
format = '[$output](blue) '
shell = ['bash', '--noprofile', '--norc']
